version: '1.0.{build}'
assembly_info:
  patch: true
  file: Program.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props;**\*.fsproj;**\*.xml'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'